### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "firstName": "1Sardorbek",
  "lastName": "1Uktamov",
  "username": "uktamov9198@mail.ru",
  "password": "O.Fozilov",
  "phoneNumber": "998995551232",
  "email": "aaaaaa998995@mail.ru"
}

### Registration verification
GET http://localhost:8080/auth/registration/verification/{profileId}