spring:
  application:
    name: bazaar
  datasource:
    url: jdbc:postgresql://localhost:5432/bazaar
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080