#########################
#       DATABASE
#########################
spring:
  application:
    name: bazaar
  datasource:
    url: jdbc:postgresql://localhost:5432/bazaar
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080

#########################
#       EMAIL SENDING
#########################

  mail:
    host: smtp.mail.ru
    port: 465
    username: sardorbek.uktamov.1@mail.ru
    password: eu7fX23a1F9eFrGCywNG
    protocol: smtps
    smtp:
      auth: true
      connectiontimeout: 50000
      timeout: 50000
      writetimeout: 50000